export interface CommunityMember {
  id: string;
  name: string;
  role: 'admin' | 'member';
}

export const admins: CommunityMember[] = [
  { id: '1', name: 'erruuu', role: 'admin' },
  { id: '2', name: 'youttaa', role: 'admin' },
  { id: '3', name: 'gaesaekkiyashibal', role: 'admin' },
  { id: '4', name: 'ohhaewonniez', role: 'admin' },
  { id: '5', name: 'aetyphia', role: 'admin' },
  { id: '6', name: 'DainsleifRil', role: 'admin' },
  { id: '7', name: 'Absrdd1', role: 'admin' },
  { id: '8', name: 'jabami_yumekoo_chan', role: 'admin' },
  { id: '9', name: 'cigarliaox', role: 'admin' },
  { id: '10', name: 'ninomataa', role: 'admin' },
  { id: '11', name: 'yoo nichol.', role: 'admin' },
  { id: '12', name: 'c', role: 'admin' },
  { id: '13', name: 'Light_ill', role: 'admin' },
  { id: '14', name: 'evellmaoi', role: 'admin' },
  { id: '15', name: 'Anomaliii', role: 'admin' },
];

export const members: CommunityMember[] = [
  { id: '16', name: '𝓛𝔂𝓷𝓷', role: 'member' },
  { id: '17', name: 'sinclair.', role: 'member' },
  { id: '18', name: 'Miawing', role: 'member' },
  { id: '19', name: 'zenn', role: 'member' },
  { id: '20', name: 'nanashi', role: 'member' },
  { id: '21', name: 'kleeicy', role: 'member' },
  { id: '22', name: '𝑯𝒆𝒏𝒓𝒚 𝑴𝒐𝒓𝒐𝒛𝒌𝒐', role: 'member' },
  { id: '23', name: 'jul\'s chlyn. (pamungkassgirl)', role: 'member' },
  { id: '24', name: 'Nyxie.', role: 'member' },
  { id: '25', name: 'Ubi', role: 'member' },
  { id: '26', name: 'kryy gantenk kata mamah', role: 'member' },
  { id: '27', name: 'saito', role: 'member' },
  { id: '28', name: 'KALDR1CK', role: 'member' },
  { id: '29', name: 'oh eto', role: 'member' },
  { id: '30', name: 'ciel', role: 'member' },
  { id: '31', name: 'miss andriana', role: 'member' },
  { id: '32', name: 'z𝓸𝓻𝓪', role: 'member' },
  { id: '33', name: 'ami! 🕉️', role: 'member' },
  { id: '34', name: 'xylns n dream.', role: 'member' },
  { id: '35', name: 'no have existence.', role: 'member' },
  { id: '36', name: 'tatsumii', role: 'member' },
  { id: '37', name: 'pryy🪽', role: 'member' },
  { id: '38', name: 'ㅤjez.', role: 'member' },
  { id: '39', name: 'Leoo', role: 'member' },
  { id: '40', name: 'Rafael', role: 'member' },
  { id: '41', name: 'Uky', role: 'member' },
  { id: '42', name: '𝐋𝐢𝐦𝐛𝐨.', role: 'member' },
  { id: '43', name: 'meo aja', role: 'member' },
  { id: '44', name: 'HaLcYoN', role: 'member' },
  { id: '45', name: 'naye', role: 'member' },
  { id: '46', name: '͏͏͏͏͏͏c', role: 'member' },
  { id: '47', name: 'ilo', role: 'member' },
  { id: '48', name: 'Shyn', role: 'member' },
  { id: '49', name: 'ciona', role: 'member' },
  { id: '50', name: 'floreiy', role: 'member' },
  { id: '51', name: 'seanmbud', role: 'member' },
  { id: '52', name: 'kiji dè lucian', role: 'member' },
  { id: '53', name: 'Aven', role: 'member' },
  { id: '54', name: '𝐀𝐝𝐚𝐦Xberli', role: 'member' },
  { id: '55', name: 'ᅠ𝗷𝗼𝗲', role: 'member' },
  { id: '56', name: 'higuruma', role: 'member' },
  { id: '57', name: 'SuperMinke-', role: 'member' },
  { id: '58', name: 'ㅤbells', role: 'member' },
  { id: '59', name: 'cathstexu', role: 'member' },
  { id: '60', name: 'Mbut mengetik....', role: 'member' },
  { id: '61', name: 'whenyh', role: 'member' },
  { id: '62', name: 'kavian', role: 'member' },
  { id: '63', name: '亲爱的', role: 'member' },
  { id: '64', name: 'bebe', role: 'member' },
  { id: '65', name: 'deren prker', role: 'member' },
];

export const communityStats = {
  totalMembers: '15k+',
  chatPerDay: '20k',
  foundedDate: '29 Oktober 2020',
  telegramLink: 'https://t.me/grup_anime_indo',
  communityName: 'Anime Lovers Indo',
  tagline: 'ANILO',
};
