name: Auto Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy
          cp -r dist/public/* deploy/
          echo "jksubindo.eu.org" > deploy/CNAME

      - name: Deploy to GitHub Pages repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd deploy
          git init
          git branch -M main
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "deploy"

          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/EruBot/erubot.github.io.git
          git push -f origin main
